### ISSUE TITLE
Too many files cause the program to crash

### ISSUE THREAD

**Issue by wlfzsd** [Lymphatus/caesium-image-compressor#195] opened 2023-03-16 02:40 UTC
I have 700,000 pictures that need to be compressed. It takes about an hour to import all of them into the software, but the program crashes after a few minutes of compression.

**Comment by Lymphatus** [comment] 2023-03-17 10:36
Can you try compressing with the "Multithreading" option unchecked? It would take much longer, but it consumes way less resources.

**Comment by wlfzsd** [comment] 2023-03-18 03:19
> 您可以尝试在未选中“多线程”选项的情况下进行压缩吗？这将花费更长的时间，但它消耗的资源更少。

The program still crashed even though I used a single thread, probably because it ran for an extended period of time.

**Comment by Lymphatus** [comment] 2023-03-31 10:11
Can it be related to #178?

**Comment by Lymphatus** [comment] 2023-04-08 11:25
The problem is most likely related to https://github.com/Lymphatus/caesium-image-compressor/issues/178#issuecomment-1500871157
Will be fixed in the next relase.

**Comment by Lymphatus** [comment] 2023-04-30 12:30
Fixed in 2.4.0

**Closed by Lymphatus** 2023-04-30 12:30 UTC
Labels: bug
