### ISSUE TITLE
File-/pathname problems with umlauts (äöüß) and more than one dot (.) in filename

### ISSUE THREAD

**Issue by miridigital** [Lymphatus/caesium-image-compressor#53] opened 2021-04-22 10:40 UTC
If the file- or pathname has german characters like umlauts (ÄÖÜäöüß) the picture(s) are not converted (red dot before filename instead of a green dot and nothing was created).

The second problem occurs if there is more than one dot (.) in filename:
Source: Prof. Bauer-4711.jpg
Target: Prof_caesium. Bauer-4711.jpg
Expected: Prof. Bauer-4711_caesium.jpg
Maybe you can use only the most right dot in filename?

And the third thing (maybe not a bug but a feature request):
If I choose the target folder and uncheck "Same folder as input" the option "Keep folder structure" is greyed out. It would be great to use this feature too. If I didn't want to save the files in the source directory structure but save it to another directory, all the files will be saved in the same target directory despite of any folder structure.
It would be perfect if I could save the complete file and folder structure to a new directory (original => compressed) with the same path and filenames but compressed.

Tested version: caesium-image-compressor-2.0.0-alpha.3-win.zip under Windows 10 Professional 64 Bit (German)

Thanks,
Miriam

**Comment by Lymphatus** [comment] 2021-04-23 11:04
Hi Miriam and thanks for the feedback!
I'm gonna have some tests about the german characters, but it might be the same bug as #31. The issue is related to the underlying library powering Caesium. I'm trying to solve that, but it may require some time. Please try the workaround on the #31 (my last comment). About the dots, it's probably just a plain bug I'm gonna address.

The third: it's a bug of the checkboxes, it should work as you said. In the alpha-4 (which I should release soon) this is fixed.

**Comment by miridigital** [comment] 2021-04-23 22:06
Hi Matteo - thank you very much for all your work and the fast response!
If have just tested the UTF-8 setting you mentioned and yes I can confirm it is working fine if UTF-8 is enabled and Windows rebooted once. That's a cool workaround - maybe not for all people (it could cause further problems with other programs if enabled) but it is still a good and easy method! Maybe you could check all input/output file-/pathnames for "problematic" characters and if so show a warning message and link to the solution/workaround? Or you could try to create a file or directory with umlaut at program start and if it doesn't work show the possible workaround. Or is there a possibility to ask the library programmer to update his software to support "special characters"?
Anyway: Thank you for the solution that works for me!

About the other two things: That would be so cool if you could find some time and patience to fix it.

I have just found the "caesiumclt" command line tool. Would this be an alternative method to convert the pictures or is it the same as the GUI version (umlauts, dots, "recursive target directory")?

Best, Miriam

**Comment by Lymphatus** [comment] 2021-04-25 16:08
caesiumclt is very similar to this project, just a different interface. It shares the non-ASCII characters issue, but not the dots or recursive directory. As I told you, some of the underlying libraries are very old and complex and won't probably change ever, so this problem might be here forever.

On the bright side, I'm currently working on a refactoring of libcaesium using Rust instead of C and **maybe** the UTF-8 chars issue can be fixed with it. It has a very long way to go, so I'll probably point to the workaround somewhere in the UI.

I'm releasing the alpha-4, you should find most of the fixes you requested.

**Comment by miridigital** [comment] 2021-04-26 13:32
Cool thank you for the updated version! I've just tested Alpha 4 and it worked fine for most of my files. Only if there is an additional dot (.) in the filename it can't convert it. An additional dot was working in Alpha 3 but the position of the suffix was put at the first (left most) dot instead of the last (right most):

äöüÄÖÜß.jpg is working fine with UTF-8 setting! (umlauts, sharp s)
test.jpg is working fine
t.est.jpg doesn't convert
dr. test.jpg doesn't convert
dir.ectory\test.jpg is working fine (directories seems to work with a dot)

How can I terminate the converting process? If there are many files and I want to close the processing window to stop the conversion it runs on and on until I wait to the end or kill the process.

cu, Miriam

**Comment by Lymphatus** [comment] 2021-04-26 15:37
Odd, I was pretty sure i got the dots problem. Seems I was wrong :( I'll check it out for the next release.

Unfortunately, you can't stop the process right now. It's something I need to work on yet.

**Comment by Lymphatus** [comment] 2021-07-24 14:39
@miridigital alpha.5 should have solved the UTF-8 issue, even if you uncheck the Windows option. If you still have the dot problem, would you mind to open a different issue for that? I think it's better to keep those two separate. Thanks!

**Closed** 2021-07-26 08:02 UTC
Labels: bug
