### ISSUE TITLE
Dropdown menus do not appear on main display

### ISSUE THREAD

**Issue by SCSJesse** [Lymphatus/caesium-image-compressor#161] opened 2022-10-21 17:13 UTC
**Describe the bug**
If you are using multiple displays (on Windows), dropdown menus will not open on the "main display"; instead, the menu will appear at the correct Y-axis but on the edge of your other display.

**Software version**
Version 2.2.1 from September 16

**Operating System information**
 - OS: Windows
 - Version: 10 [21H2]

**To Reproduce**
1. Use a desktop with 2 monitors
2.  Assign a "main display" to one of the monitors
3. Run the software and use it on aforementioned "main display" monitor
4. Select any given dropdown from the ribbon or panels
5. Menu appears on other screen

**Expected behavior**
Any window/dropdown should open on the display that the software window is floating/appearing on.

**Screenshots**
N/A

**Application Log**
N/A

**Additional context**
If you hook up additional monitors (3 or more) and have at least 1 display on each side of the primary display, the drop down will appear on whichever display you most recently moved the application window from.

**Comment by Lymphatus** [comment] 2022-11-01 15:58
I tried to reproduce the bug on my machine, with same the OS (Windows 10, 21H2) but I seems to work fine. I tried the steps you provided and every menu, dropdown, context menu (with right click) or popup screen appears on the display the main window is running on.
Am I missing something? Can you provide a few more details please?

**Comment by SCSJesse** [comment] 2022-11-02 15:06
Hello Matteo,

I'm not sure how this issue has not presented itself on your machine as it seems to happen on mine following the steps noted above. I will perform some additional troubleshooting on my end and respond with any previously undiscovered factors if they arise, this is a minor issue that does not affect the other functionality of the software.

Thank you.

**Comment by Lymphatus** [comment] 2022-11-02 15:47
While trying to reproduce this bug I found there's an issue with multiple monitor when you first open Caesium on Monitor 1, then close it and disable Monitor 2. Caesium should appear on Monitor 2 (the last remaining) if you reopen the app again, but instead is "stuck" on an invisible monitor. Fixing this may also fix your issue, even though I can't really get it to occur on my side.

**Comment by jonaslewin** [comment] 2022-11-08 16:42
The same issue exists on Windows 11.
Running the software on the main display shows the menu on the other display.

Setup: Main display left, other display right.
Starting the software on virtual desktop 1.

**Comment by dbrasseur-aneo** [comment] 2022-11-24 19:03
Same issue here

**Comment by Lymphatus** [comment] 2023-01-23 10:54
Tentative fix in [v2.3.0](https://github.com/Lymphatus/caesium-image-compressor/releases/tag/v2.3.0)

**Comment by jonaslewin** [comment] 2023-01-24 05:32
The issue remains in v2.3.0.
As you can see from the background of the two monitors, this is how it looks.
![image](https://user-images.githubusercontent.com/3225633/214219078-09b697d1-5ca8-4152-8218-801c3192096c.png)

When I start the program, it starts on the 2nd monitor (not the main monitor). 
I launched the exe file from explorer on the main monitor.

**Comment by Lymphatus** [comment] 2023-01-31 10:35
Maybe I found why I could not reproduce the issue. Are your monitors all the same model? Mine are different and the issue does not occur.
It's probably a [Qt bug](https://bugreports.qt.io/browse/QTBUG-103854?jql=text%20~%20%22multiple%20monitors%22). but I'm releasing the next version of Caesium with an updated Qt version, so it should be fixed, hopefully.

**Comment by Lymphatus** [comment] 2023-02-13 07:24
Fixed in [v2.3.1](https://github.com/Lymphatus/caesium-image-compressor/releases/tag/v2.3.1)

**Closed by Lymphatus** 2023-02-13 07:24 UTC
Labels: bug

**Comment by jonaslewin** [comment] 2023-02-13 07:37
Tested and it works as expected now. Thank you @Lymphatus.
