### ISSUE TITLE
add possibility to compress directly through contextual menu (windows)

### ISSUE THREAD

**Issue by Asgatlat** [Lymphatus/caesium-image-compressor#113] opened 2022-05-06 09:20 UTC
is it possible to add in the contextual menu the possibility to compress a picture :
on windows, in file explorer, do a right click on a picture file and select "compress with Caesium"
same for a folder

**Comment by Lymphatus** [comment] 2022-05-06 12:55
Duplicate of #26

**Closed by Lymphatus** 2022-05-06 12:55 UTC
Labels: duplicate, feature request
