### ISSUE TITLE
Ceasium's modals and pull-down menus opening on the wrong monitor.

### ISSUE THREAD

**Issue by Sennik** [Lymphatus/caesium-image-compressor#184] opened 2023-01-31 09:35 UTC
First of all, in general, love this little tool and I for sure will donate!

**Software version**
2.3.0

**Operating System information**
 - OS: Windows
 - Version 11

**To Reproduce**
Use multiple monitors, I use three of the same in the order [2] [1] [3] (The middle monitor is my primary monitor).

1. Open Caesium Image Compressor (CIC)
CIC opens default on monitor 3
2. Move (drag) CIC to monitor 1
3. Drag and drop a couple of images to CIC to compress
4. Click 'Compress'
The confirmation modal pops-up at monitor 3
5. Confirm
After compressing is finished the modal with job statistics opens on monitor 3

Also, the pull-down menu's of CIC are opening on monitor three (left-top edge) whiles Ceasium is still on Monitor 2

**What Have I tried**
1. Closing and opening CIC
CIC opens on monitor 1 (prefereered behavior, open on the same monitor where it was closed), so this is good.
Rest is still wrong, see previous description.

2. Use Powertoys' FancyZones 
Configure FZ to open windows at there previous position
Same as above.

This is quiet annoying.

**Comment by Lymphatus** [comment] 2023-01-31 09:47
Probably a duplicate of #161. Thanks for the detailed description.

**Comment by Lymphatus** [comment] 2023-02-13 07:24
Fixed in [v2.3.1](https://github.com/Lymphatus/caesium-image-compressor/releases/tag/v2.3.1)

**Closed by Lymphatus** 2023-02-13 07:24 UTC
Labels: bug
