### ISSUE TITLE
HDR photos are not compressed correctly

### ISSUE THREAD

**Issue by ThePhoenixCoding** [Lymphatus/caesium-image-compressor#301] opened 2024-09-24 12:27 UTC
**Describe the bug**
When compressing HDR photos as the Google Pixel 9 Pro (XL) takes them from JPEG to JPEG, two issues occur:
- The HDR information seems to be lost. Though the color range in the image metadata is unchanged, neither my MacBook Pro (2021, M1) nor my Google Pixel 9 Pro XL displays the image as HDR anymore
- When just changing quality and not the resolution, the MacBook Pro can't display the image anymore. As soon as it re-renders the image after opening it (by double clicking it, not by pressing space to preview), it turns black.

**Software version**
v. 2.7.1

**Operating System information**
 - OS: MacOs 15 sequoia

**To Reproduce**
1. Take a picture with the Google Pixel 9 Pro XL
2. Select format "as original", quality 80 for JPEG
3. Optionally select "resize image" and use 50% width and 50% height (see above)
4. Compare the resulting image with the original on your MacBook Pro internal display (for HDR) or on your Pixel 9 Pro

**Expected behavior**
The resulting image looks mostly like the original, containing HDR information and being displayed as such

**Application Log**
[caesium-2024-09-24.log](https://github.com/user-attachments/files/17114480/caesium-2024-09-24.log)

**Comment by Lymphatus** [comment] 2024-09-24 14:26
Do you have a sample picture so I can try to reproduce the issue? I don't have a Pixel 9 but can check with my MacBook if you can provide an HDR photo. Thanks!

**Comment by ThePhoenixCoding** [comment] 2024-09-24 16:22
![compressed](https://github.com/user-attachments/assets/68a9d012-eb99-48e7-ae6d-1d8a95d53710)
![HDR](https://github.com/user-attachments/assets/7f86f818-3c1d-4a85-8cf9-6430d71b2bf4)

Sure :) Thanks for reacting so quickly!

**Comment by Lymphatus** [comment] 2024-09-26 08:15
Just tested with my MacbookPro (M3, Sonoma 14.6.1) and both images look pretty much identical. I can see the compressed one just fine in Preview and by tapping spacebar on the Finder. Can you re-upload them in a .zip archive? I suspect uploading to Github might compromise something. Thanks!

**Comment by ThePhoenixCoding** [comment] 2024-09-26 13:31
[Archiv.zip](https://github.com/user-attachments/files/17149141/Archiv.zip)

When I download the images from Github, i get the same effects: The HDR is a lot brighter on the internal display until MacOS re-renders it and it turns black blockwise (and when viewed on the external non-HDR-compatible display, the sky is a bit less contrasty, so they definitely are differentiable on my end). The image sizes also are identical to the ones before uploading.
But nonetheless, here they are again in a ZIP :)

What it looks like here:
![Bildschirmfoto 2024-09-26 um 15 27 31_compressed](https://github.com/user-attachments/assets/77f74f33-06b3-41f7-a6d1-099be8aa7fe1)

**Comment by Lymphatus** [comment] 2024-09-28 09:33
Updated my MacBook to Sequoia 15.0 and shows the same problem as you. This is quite interesting and I need to further investigate to figure out what's going on with HDR pictures and the new macOS. Thanks for reporting!

**Comment by ThePhoenixCoding** [comment] 2024-09-28 12:03
Thanks so much for investigating!
I think it's interesting that the compressed image can be displayed on the Pixel, but also is not shown as HDR there, just like the compressed + resized version on MacOS. Looks like the "this is an HDR image" info itself breaks in some way which Mac and the Pixel interprete differently then.

I'm gladful that you look into it and I'm curious if this can be fixed!

**Comment by Lymphatus** [comment] 2024-09-30 18:03
I've done some research.
Turns out that the Ultra HDR image of the Pixels is a [specific Google library](https://github.com/google/libultrahdr) that can decode/encode images in a backward compatibility way, so they can be displayed all across devices. This unfortunately means that no JPEG library (Caesium uses mozjpeg) can really manage the HDR info right out the box. The only way I can think of is implement the library inside Caesium and treat them as a separate format, but this would require quite a bit of work for a very specific use case.
I'd be curios to see if there's any compression tool out there capable of handling this format. I tried Squoosh, which is somehow related to Google and pretty much is the same as Caesium.

I might close this out as "won't fix", since it's a very specific issue that I'm not able to address correctly. I might think in the future to try strip out the EXIF into that tell that the image is HDR so MacOS can correctly open it.
If you find out more, feel free to comment further.

On a side note, default photo app on Windows cannot display the HDR version of the image and always shows the SDR. A way to see the HDR image is to load it into Chrome, which - of course - supports the Ultra HDR. Chrome shows the compressed image as SDR correctly, so it might also be a bug on the MacOS Preview app.

**Closed by Lymphatus** 2024-09-30 18:03 UTC
Labels: bug
